name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ganti dengan branch yang kamu gunakan untuk deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Ganti dengan versi Node.js yang kamu butuhkan

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Pastikan script build ada di package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Ganti dengan direktori build kamu
